# This workflow file is named 'more-ci' and is used to run additional CI checks
# that complement the main CI workflow. It ensures that our code is tested
# across multiple operating systems and OCaml compiler versions.
#
# Compared to the main 'ci.yml' job, this skips some steps that are not
# necessary to check for every combination of os and ocaml-compiler, such as
# generating coverage report, linting odoc, opam and fmt, etc.
#
# We prefer to keep it separate from the main CI workflow because we find it
# more readable, over having too many conditional steps in the same job.

name: more-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.4.x
          - 5.3.x
          - 5.2.x
        exclude:
          # We exclude the combination already tested in the 'ci' workflow.
          - os: ubuntu-latest
            ocaml-compiler: 5.4.x

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install sdl2 dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-image-dev

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@dec6499fef64fc5d7ed43d43a87251b7b1c306f5 # v3.4.8
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            mbarbin: https://github.com/mbarbin/opam-repository.git
      #     alpha:   https://github.com/kit-ty-kate/opam-alpha-repository.git
      #     janestreet-bleeding: https://github.com/janestreet/opam-repository.git
      #     janestreet-bleeding-external: https://github.com/janestreet/opam-repository.git#external-packages

      - name: Environment setup
        run: |
          if [ "${{ matrix.ocaml-compiler }}" = "5.2.x" ]; then
            echo "PACKAGES=bopkit,subleq,visa" >> "$GITHUB_ENV"
            echo "OPAM_PACKAGES=./bopkit.opam ./subleq.opam ./visa.opam" >> "$GITHUB_ENV"
          else
            echo "PACKAGES=bopkit,bopkit-tests,subleq,visa" >> "$GITHUB_ENV"
            echo "OPAM_PACKAGES=./bopkit.opam ./bopkit-tests.opam ./subleq.opam ./visa.opam" >> "$GITHUB_ENV"
          fi

      # We build and run tests for a subset of packages. More tests are run in
      # the development workflow and as part of the main CI job. These are the
      # tests that are checked for every combination of os and ocaml-compiler.
      - name: Install dependencies
        run: opam install ${{ env.OPAM_PACKAGES }} --deps-only --with-test

      - name: Build & Run tests
        run: opam exec -- dune build @all @runtest --only-packages=${{ env.PACKAGES }}
